---
headerStyle: boxedWidgets
fullWidth: true
useEqualHeights: false

layout:
  Watch:
    icon: mdi-play-circle
    style: row
    columns: 3
  Media Library:
    icon: mdi-multimedia
    style: row
    columns: 4
  Media Automation:
    icon: mdi-download
    style: row
    columns: 4
  Smart Home:
    icon: mdi-home-automation
    style: row
    columns: 2
  Network:
    icon: mdi-network
    style: row
    columns: 3
  Server Management:
    icon: mdi-server
    style: row
    columns: 3
