---
headerStyle: boxedWidgets
fullWidth: true
useEqualHeights: false

layout:
  Left Column:
    header: false
    style: column
    Watch:
      icon: mdi-play-circle
      style: column
    Media Automation:
      icon: mdi-download
      style: column
  Middle Column:
    header: false
    style: column
    Media Library:
      icon: mdi-multimedia
      style: column
    Smart Home:
      icon: mdi-home-automation
      style: column
  Right Column:
    header: false
    style: column
    Network:
      icon: mdi-network
      style: column
    Server Management:
      icon: mdi-server
      style: column
