services:
  whatsupdocker:
    image: getwud/wud:9.1.0
    container_name: wud
    restart: unless-stopped
    labels:
      - wud.watch=true
      - homepage.group=Server Management
      - homepage.name=What's Up Docker
      - homepage.weight=20
      - homepage.icon=whats-up-docker.png
      - homepage.href=https://wud.bullman.net
      - homepage.description=Docker Maintenance
      - homepage.widget.type=whatsupdocker
      - homepage.widget.url=http://192.168.0.250:3001
      - homepage.widget.fields=["monitoring", "updates"]
      - homepage.widget.key=${WUD_HOMEPAGE_API_TOKEN:?Set WUD_HOMEPAGE_API_TOKEN in Portainer}
    volumes:
      - /Volume1/public/docker-configs/wud:/store
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Los_Angeles
      - WUD_AUTH_ADMIN_USER=admin
      - WUD_AUTH_ADMIN_PASSWORD=${WUD_ADMIN_PASSWORD:?Set WUD_ADMIN_PASSWORD in Portainer}
      - WUD_WATCHER_LOCAL_CRON=0 0 19 * * *
      - WUD_WATCHER_LOCAL_WATCHBYDEFAULT=false
      - WUD_REGISTRY_HUB_PUBLIC_WATCHDIGEST=true
      - WUD_TRIGGER_DOCKER_LOCAL_AUTO=true
      - WUD_TRIGGER_DOCKER_LOCAL_PRUNE=true
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - 3001:3000
